[package]
name = "muxw"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.0"

authors = ["Mikołaj Kozłowski <kozlowski.g.mikolaj@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/Fasamii/muxw"
description = "Hyperextensible Wayland compositor"

[dependencies]
muxw-types = { path = "../muxw-types/" }

slab = "0.4.12"
multi_index_map = "0.15.1"

clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }

polling = "3.11.0"
crossbeam-channel = "0.5.15"

udev = "0.9.3"
input = "0.9.1"
xkbcommon = "0.9.0"

mlua = { version = "0.11.5", default-features = false, features = [
	"luajit52",
	"vendored",
	"serialize",
] }

ash = "0.38.0"
gbm = "0.18.0"
drm = "0.14.1"
wayland-server = { version = "0.31.10", default-features = false }
wayland-backend = "0.3.11"
wayland-protocols = { version = "0.32.9", features = ["server", "staging"] }


rustix = "1.1.4"
bitflags = "2.11.0"
rustc-hash = "2.1.2"

[build-dependencies]
clap_complete = "4.5.65"
clap = { version = "4.5.54", features = ["derive"] }
