[package]
name = "muxw"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.0"

authors = ["Mikołaj Kozłowski <kozlowski.g.mikolaj@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/Fasamii/muxw"
description = "muxw wayland compositor"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
incremental = false
overflow-checks = false

[profile.release-debug]
inherits = "release"
debug = 1
strip = "none"

[dependencies]
muxw-types = { path = "../muxw-types/" }
muxw-bind-epoll = { path = "../muxw-bind-epoll/" }

bitflags = "2.10.0"

clap = { version = "4.5.54", features = ["derive"] }
clap_complete = "4.5.65"

serde = { version = "1.0.228", features = ["derive"] }
mlua = { version = "0.11.5", default-features = false, features = [
	"luajit52",
	"vendored",
	"serialize",
] }

csscolorparser = "0.8.1"


epoll = { git = "https://github.com/Fasamii/epoll.git" }
udev = "0.9.3"
input = "0.9.1"
xkbcommon = "0.9.0"

ash = "0.38.0"
gbm = "0.18.0"
drm = "0.14.1"
wayland-server = { version = "0.31.10", default-features = false }
wayland-backend = "0.3.11"
wayland-protocols = { version = "0.32.9", features = ["server", "staging"] }
arc-swap = "1.8.0"
